---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates (CentOS)
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
      tags: always

    - name: install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      tags: always

- hosts: web_servers
  become: true
  tasks:
    - name: install apache and php for Ubuntu servers
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
      tags:
        - apache
        - ubuntu

    - name: install apache and php for CentOS servers
      yum:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"
      tags:
        - apache
        - centos
        - httpd

    - name: start httpd (CentOS)
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_distribution == "CentOS"
      tags:
        - apache
        - centos
        - httpd

- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package (CentOS)
      yum:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "CentOS"
      tags:
        - centos
        - db
        - mariadb

    - name: "Mariadb - Restarting/Enabling"
      service:
        name: mariadb
        state: restarted
        enabled: true
      tags:
        - db
        - mariadb

    - name: install mariadb package (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"
      tags:
        - db
        - mariadb
        - ubuntu

- hosts: file_server
  become: true
  tasks:
    - name: install samba package
      package:
        name: samba
        state: latest
      tags:
        - samba

